test_task:
  container:
    matrix:
      image: bash:5.0
      image: bash:4.4
      image: bash:4.3
      image: bash:4.2
      image: bash:4.1
      image: bash:4.0
  test_script: 
    - bash --version
    - cd example
    - ./array.sh  
    - ./human.sh  
    - ./string.sh  
    - ./testing.sh
    - ./trycatch.sh
