test_task:
  #container:
    #image: gradle:jdk8
    #cpu: 4
    #memory: 10G
  test_script: 
    - bash --version
    - cd example
    - ./array.sh  
    - ./human.sh  
    - ./string.sh  
    - ./testing.sh
    - ./trycatch.sh
