install:
  - apt-cache policy bash gcc make
  - bash --version
  - sudo apt-get -y bash install build-essential
  - bash --version
  - gcc -v
  - make -v
  - wget http://ftp.gnu.org/gnu/bash/bash-4.4.tar.gz
  - tar xf bash-4.4.tar.gz
  - cd bash-4.4
  - ./configure
  - make
  - cd ..
  - export PATH=$PWD/bash-4.4:$PATH
  - bash --version
script:
  - cd example
  #- for f in *.sh; do ./$f; done
  - ./array.sh  
  - ./human.sh  
  - ./string.sh  
  #- ./testing.sh  
  - ./trycatch.sh
