# upgrade to bash 4.4
install:
  - apt-cache policy bash gcc make
  - bash --version
  # install gcc and make
  - sudo apt-get -y install build-essential
  - gcc -v
  - make -v
  - wget http://ftp.gnu.org/gnu/bash/bash-4.4.tar.gz
  - tar xf bash-4.4.tar.gz
  - cd bash-4.4
  - ./configure
  - make
  - cd ..
  - export PATH=$PWD/bash-4.4:$PATH
  - bash --version

# run examples
script:
  - cd example
  - ./array.sh  
  - ./human.sh  
  - ./string.sh  
  #- ./testing.sh  hanging
  - ./trycatch.sh
